// flow-typed signature: d54fc0ccb4add292d3dc956e9cdfeb1d
// flow-typed version: <<STUB>>/jsdom_v^6.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdom/lib/base64' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/default-stylesheet' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/documentAdapter' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/documentfeatures' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/domtohtml' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/history' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/htmltodom' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/location' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/not-implemented' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/resource-loader' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/Window' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/events/EventTarget' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level1/core' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/core' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/events' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/html' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/languages/javascript' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/style' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level3/core' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level3/ls' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level3/xpath' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/attributes' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/character-data' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/comment' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/document-type' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/document' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/dom-implementation' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/dom-token-list' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/element' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/error-event' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/hash-change-event' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/document-base-url' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/internal-constants' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/ordered-set-parser' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/proxied-window-event-handlers' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/runtime-script-errors' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/validate-names' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/html-collection' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/index' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/message-event' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/named-properties-window' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node-filter' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node-iterator' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node-list' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node-type' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/non-document-type-child-node' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/parent-node' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/post-message' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/processing-instruction' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/selectors' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/text' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/url' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/named-properties-tracker' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/utils' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/virtual-console' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/vm-shim' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/web-idl/DOMException' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdom/lib/base64.js' {
  declare module.exports: $Exports<'jsdom/lib/base64'>;
}
declare module 'jsdom/lib/jsdom.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom'>;
}
declare module 'jsdom/lib/jsdom/browser/default-stylesheet.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/default-stylesheet'>;
}
declare module 'jsdom/lib/jsdom/browser/documentAdapter.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/documentAdapter'>;
}
declare module 'jsdom/lib/jsdom/browser/documentfeatures.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/documentfeatures'>;
}
declare module 'jsdom/lib/jsdom/browser/domtohtml.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/domtohtml'>;
}
declare module 'jsdom/lib/jsdom/browser/history.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/history'>;
}
declare module 'jsdom/lib/jsdom/browser/htmltodom.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/htmltodom'>;
}
declare module 'jsdom/lib/jsdom/browser/location.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/location'>;
}
declare module 'jsdom/lib/jsdom/browser/not-implemented.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/not-implemented'>;
}
declare module 'jsdom/lib/jsdom/browser/resource-loader.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/resource-loader'>;
}
declare module 'jsdom/lib/jsdom/browser/Window.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/Window'>;
}
declare module 'jsdom/lib/jsdom/events/EventTarget.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/events/EventTarget'>;
}
declare module 'jsdom/lib/jsdom/level1/core.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level1/core'>;
}
declare module 'jsdom/lib/jsdom/level2/core.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/core'>;
}
declare module 'jsdom/lib/jsdom/level2/events.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/events'>;
}
declare module 'jsdom/lib/jsdom/level2/html.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/html'>;
}
declare module 'jsdom/lib/jsdom/level2/languages/javascript.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/languages/javascript'>;
}
declare module 'jsdom/lib/jsdom/level2/style.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/style'>;
}
declare module 'jsdom/lib/jsdom/level3/core.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level3/core'>;
}
declare module 'jsdom/lib/jsdom/level3/ls.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level3/ls'>;
}
declare module 'jsdom/lib/jsdom/level3/xpath.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level3/xpath'>;
}
declare module 'jsdom/lib/jsdom/living/attributes.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/attributes'>;
}
declare module 'jsdom/lib/jsdom/living/character-data.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/character-data'>;
}
declare module 'jsdom/lib/jsdom/living/comment.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/comment'>;
}
declare module 'jsdom/lib/jsdom/living/document-type.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/document-type'>;
}
declare module 'jsdom/lib/jsdom/living/document.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/document'>;
}
declare module 'jsdom/lib/jsdom/living/dom-implementation.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/dom-implementation'>;
}
declare module 'jsdom/lib/jsdom/living/dom-token-list.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/dom-token-list'>;
}
declare module 'jsdom/lib/jsdom/living/element.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/element'>;
}
declare module 'jsdom/lib/jsdom/living/error-event.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/error-event'>;
}
declare module 'jsdom/lib/jsdom/living/hash-change-event.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/hash-change-event'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/document-base-url.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/document-base-url'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/internal-constants.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/internal-constants'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/ordered-set-parser.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/ordered-set-parser'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/proxied-window-event-handlers.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/proxied-window-event-handlers'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/runtime-script-errors.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/runtime-script-errors'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/validate-names.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/validate-names'>;
}
declare module 'jsdom/lib/jsdom/living/html-collection.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/html-collection'>;
}
declare module 'jsdom/lib/jsdom/living/index.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/index'>;
}
declare module 'jsdom/lib/jsdom/living/message-event.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/message-event'>;
}
declare module 'jsdom/lib/jsdom/living/named-properties-window.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/named-properties-window'>;
}
declare module 'jsdom/lib/jsdom/living/node-filter.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node-filter'>;
}
declare module 'jsdom/lib/jsdom/living/node-iterator.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node-iterator'>;
}
declare module 'jsdom/lib/jsdom/living/node-list.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node-list'>;
}
declare module 'jsdom/lib/jsdom/living/node-type.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node-type'>;
}
declare module 'jsdom/lib/jsdom/living/node.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node'>;
}
declare module 'jsdom/lib/jsdom/living/non-document-type-child-node.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/non-document-type-child-node'>;
}
declare module 'jsdom/lib/jsdom/living/parent-node.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/parent-node'>;
}
declare module 'jsdom/lib/jsdom/living/post-message.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/post-message'>;
}
declare module 'jsdom/lib/jsdom/living/processing-instruction.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/processing-instruction'>;
}
declare module 'jsdom/lib/jsdom/living/selectors.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/selectors'>;
}
declare module 'jsdom/lib/jsdom/living/text.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/text'>;
}
declare module 'jsdom/lib/jsdom/living/url.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/url'>;
}
declare module 'jsdom/lib/jsdom/named-properties-tracker.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/named-properties-tracker'>;
}
declare module 'jsdom/lib/jsdom/utils.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/utils'>;
}
declare module 'jsdom/lib/jsdom/virtual-console.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/virtual-console'>;
}
declare module 'jsdom/lib/jsdom/vm-shim.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/vm-shim'>;
}
declare module 'jsdom/lib/jsdom/web-idl/DOMException.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/web-idl/DOMException'>;
}
